# Generated by Django 2.1 on 2018-08-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('workout_type', models.CharField(choices=[('trainer', 'Trainer'), ('road', 'Road')], default='road', max_length=100)),
                ('effort_types', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='easy', max_length=100)),
                ('distance', models.FloatField(blank=True)),
                ('speed', models.FloatField(blank=True)),
                ('time', models.FloatField(blank=True)),
                ('notes', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
